# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ddc60fa091d1c25f874825ad1dfbe4852532dfc3e66a1281de6d0be26c24fefabdcc62b591cdec533fd7cf7e2b535eb135ce11d1e699ca3233bbff89ad05775

test:
  secret_key_base: eb6f737cda5a4633be7c99610352efa5b4bdfef109da81c107f34a156e97bc0da964a83f278e91a699c455d7e61c89864cdd015b53d1c15ba0e9958e25cb243f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
